// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: eventstream/message-metadata.proto

package eventstream

import (
	"reflect"
	"sync"
	"unsafe"

	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
	"google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Standard metadata that can be attached to any event envelope message.
type MessageMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageMetadata) Reset() {
	*x = MessageMetadata{}
	mi := &file_eventstream_message_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageMetadata) ProtoMessage() {}

func (x *MessageMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_eventstream_message_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageMetadata.ProtoReflect.Descriptor instead.
func (*MessageMetadata) Descriptor() ([]byte, []int) {
	return file_eventstream_message_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *MessageMetadata) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *MessageMetadata) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

var File_eventstream_message_metadata_proto protoreflect.FileDescriptor

const file_eventstream_message_metadata_proto_rawDesc = "" +
	"\n" +
	"\"eventstream/message-metadata.proto\x12\veventstream\x1a\x1fgoogle/protobuf/timestamp.proto\"i\n" +
	"\x0fMessageMetadata\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAtB3Z1pkg.hexaform.dev/protogen/eventstream;eventstreamb\x06proto3"

var (
	file_eventstream_message_metadata_proto_rawDescOnce sync.Once
	file_eventstream_message_metadata_proto_rawDescData []byte
)

func file_eventstream_message_metadata_proto_rawDescGZIP() []byte {
	file_eventstream_message_metadata_proto_rawDescOnce.Do(func() {
		file_eventstream_message_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eventstream_message_metadata_proto_rawDesc), len(file_eventstream_message_metadata_proto_rawDesc)))
	})
	return file_eventstream_message_metadata_proto_rawDescData
}

var file_eventstream_message_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_eventstream_message_metadata_proto_goTypes = []any{
	(*MessageMetadata)(nil),       // 0: eventstream.MessageMetadata
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_eventstream_message_metadata_proto_depIdxs = []int32{
	1, // 0: eventstream.MessageMetadata.occurred_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_eventstream_message_metadata_proto_init() }
func file_eventstream_message_metadata_proto_init() {
	if File_eventstream_message_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eventstream_message_metadata_proto_rawDesc), len(file_eventstream_message_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eventstream_message_metadata_proto_goTypes,
		DependencyIndexes: file_eventstream_message_metadata_proto_depIdxs,
		MessageInfos:      file_eventstream_message_metadata_proto_msgTypes,
	}.Build()
	File_eventstream_message_metadata_proto = out.File
	file_eventstream_message_metadata_proto_goTypes = nil
	file_eventstream_message_metadata_proto_depIdxs = nil
}
