package internal

import "google.golang.org/protobuf/compiler/protogen"

func (o *OutputFile) GenerateHeader(file *protogen.File) {
	o.P("// Code generated by protoc-gen-go-eventstream. DO NOT EDIT.")
	o.P("// versions:")
	o.P("//  protoc-gen-go-eventstream: v0.0.1")
	o.P("// source: ", file.Proto.GetName())
	o.P()
	o.P("package ", file.GoPackageName)
	o.P()
}
